move /next to the main export, preserve older code in "/legacy"
opensouls/SocialAGI pull request #128
Opened 2023-12-18 09:28 UTC by tobowers

We recently received a bug report on some code we don't really want people using, and our discord has been asking to move the "/next" export up a level to be the main export. This PR updates the exports, the tests, and the docs to reflect how "/next" is where we really want/expect people to start.

I've preserved the "/next" export in the package.json and added a new "/legacy" export in case anyone still needs code from there.

Semantic versioning "0.1.0" should prevent anyone from getting auto-updated to this latest version.

2023-12-18 17:47 UTC, kafischer approved these changes
nice!

2023-12-19 00:56 UTC, charlesvien commented
LGTM

2023-12-19 05:31 UTC, kafischer requested changes
i think a few changes to the main readme would make sense here too

2023-12-19 09:00 UTC, tobowers commented
@kafischer updated.

2023-12-19 20:52 UTC, kafischer commented on README.md
> +/example-webapp
I wonder if we should remove all the examples and integrations rn
From those directories in root

2023-12-19 20:52 UTC, kafischer commented on README.md
> +- (slightly outdated) [`/integrations`](./integrations) contains examples of the library in action. Right now contains several stand-alone discord and telegram bot repos
should we remove?

2023-12-19 22:36 UTC, tobowers commented
@kafischer removed :)

2023-12-19 23:11 UTC, kafischer approved these changes

2023-12-20 01:32 UTC, merged