adds resetMemory function
opensouls/SocialAGI pull request #131
Opened 2023-12-26 08:10 UTC by tobowers

This allows you to to get a new CortexStep with completely updated memories. Useful for a few things, some are:

* reset memories after learning interlocutor name
* summarize early memories
* rewind to a previous state

2023-12-26 15:31 UTC, kafischer reviewed
Do we want to name it something more like `withUpdatedMemories`?

2023-12-26 18:31 UTC, tobowers commented
@kafischer used the singular to more closely match "withMemory"

2023-12-26 22:24 UTC, kafischer requested changes

2023-12-26 22:24 UTC, kafischer commented on docs/docs/CortexStep/api.md
> +   step = await step.resetMemory(memories => memories.filter(m => m.role !== "user"));
Need to update here too

2023-12-27 04:26 UTC, kafischer commented on docs/docs/CortexStep/api.md
> +   step = await step.resetMemory(memories => memories.filter(m => m.role !== "user"));
```suggestion
   step = await step.withUpdatedMemory(memories => memories.filter(m => m.role !== "user"));
```

2023-12-27 08:02 UTC, tobowers commented
@kafischer updated

2023-12-27 11:29 UTC, kafischer approved these changes

2023-12-27 13:05 UTC, merged