add actions
opensouls/SocialAGI pull request #23
Opened 2023-06-09 11:46 UTC by tobowers

This adds the ability to use "actions" in text (and this also includes #22 so can replace that PR).

So far I have only tried RAMBLE and it appears to be working really well.

2023-06-09 22:17 UTC, kafischer requested changes
AMAZING very cool addition

2023-06-09 22:17 UTC, kafischer commented on core/examples/example.ts
> +  additionalContext: `Samantha is texting someone new at MeetSamantha.ai. The time and date is: ${new Date().toLocaleString()}}`,
Should this be a conversation specific context?

2023-06-09 22:17 UTC, kafischer commented on core/src/TEMPLATES.ts
> +   <ACTION_INPUT>Any input to the action</ACTION_INPUT>
Nice! I even imagine that it generates input notes to its future self for ramble?

2023-06-09 22:17 UTC, kafischer commented on core/src/conversationProcessor.ts
> +        this.continueThinking();
would this be `conversation.genereatedThoughts ...`, `conversation.continueThinking()`, and `soul.actions`

with the signature as in the action interface for clarity?

2023-06-10 08:11 UTC, tobowers commented on core/src/TEMPLATES.ts
> +   <ACTION_INPUT>Any input to the action</ACTION_INPUT>
In my current ramble method I ask it to say "yes" or "no" but yeah notes are smart. One thing that I want to figure out on the next version of this is putting the action and the ACTION_INPUT together.

2023-06-10 08:12 UTC, tobowers commented on core/src/conversationProcessor.ts
> +        this.continueThinking();
I'm not sure exactly what you're saying here, but I think you're saying add the other two inputs next to "input"?

2023-06-10 10:05 UTC, tobowers commented on core/examples/example.ts
> +  additionalContext: `Samantha is texting someone new at MeetSamantha.ai. The time and date is: ${new Date().toLocaleString()}}`,
made this true, and showed the power of dynamic contexts in the example.

2023-06-10 10:08 UTC, tobowers commented on core/src/conversationProcessor.ts
> +        this.continueThinking();
I changed it to show the full signature - let me know if that's not what you meant.

2023-06-10 14:40 UTC, kafischer commented on core/src/conversationProcessor.ts
> +        this.continueThinking();
Am I misunderstanding or wouldn't this be more clear?

```suggestion
        conversation.generatedThoughts.push(
          new Thought({
            role: "assistant",
            entity: this.blueprint.name,
            action: "RAMBLE",
            content: "I want to ramble before they respond",
          })
        );
        conversation.continueThinking();
```

2023-06-10 14:58 UTC, tobowers commented on core/src/conversationProcessor.ts
> +        this.continueThinking();
ah good idea. made that change.

2023-06-10 15:08 UTC, kafischer approved these changes
Wohoo!

2023-06-10 15:10 UTC, merged