small cleanups
opensouls/SocialAGI pull request #61
Opened 2023-07-07 09:42 UTC by tobowers

* devLog now supports multiple non-text arguments
* CortexNext receives the step it's coming from (and memories moved to public so that they can be used)
* custom actions carried over automatically from one step to the next
* I was consistently getting some minor invalid XML, so re-inforced XML sanity in the prompt.

2023-07-08 12:52 UTC, kafischer commented
I was wondering if next should take a action class instead - so all those built in actions aren't defined on the class and new actions aren't tied to an instance

2023-07-08 16:16 UTC, kafischer commented on core/src/cortexStep.ts
> +Reply in the output format: \`${beginning}[[fill in]]</${action}>\`. Double check you are returning valid XML.
ha, nice. funny that works well

2023-07-08 16:18 UTC, kafischer requested changes

2023-07-08 16:18 UTC, kafischer commented on core/src/cortexStep.ts
> +    const nextValue = resp.slice(beginning.length);
if it's returning valid xml shouldn't we just parse greedily up to something like `/^[^>]*>{0,1}[^>]*>/g`

2023-07-08 18:25 UTC, tobowers commented on core/src/cortexStep.ts
> +    const nextValue = resp.slice(beginning.length);
yeah that's good, get rid of anything in the first two > if I read that right.

2023-07-08 18:28 UTC, tobowers commented
> I was wondering if next should take a action class instead - so all those built in actions aren't defined on the class and new actions aren't tied to an instance

Yup I definitely think it should - make using custom ones the "first class" and then include default ones in the library.

2023-07-08 19:34 UTC, tobowers commented on core/src/cortexStep.ts
> +    const nextValue = resp.slice(beginning.length);
made that change

2023-07-09 14:22 UTC, kafischer approved these changes

2023-07-09 14:23 UTC, merged