call functions and get responses
opensouls/SocialAGI pull request #77
Opened 2023-07-23 19:53 UTC by tobowers

This pull request adds a relatively simple way to expose functions to the corestep. You can force the corestep to call functions or use the normal openAI "auto" feature - as seen in the example here.

I don't suspect this will be the ultimate API, but at least it unlocks toying with functions in a way that has a consistent API.

2023-07-24 21:09 UTC, tobowers commented
@kafischer

2023-07-25 01:42 UTC, kafischer requested changes
Very cool!

I'm not sure I understand the api being withFunctions versus requiring the FunctionRunner to always be specified in a .next step- it feels like it breaks something conceptually to me

2023-07-25 01:42 UTC, kafischer commented on core/src/cortexStep.ts
> +      lastValue: memories.slice(-1)[0].content,
The function runner should probably return the lastValues well as the memories

2023-07-25 01:42 UTC, kafischer commented on core/examples/example5_functions.ts
> +// this example demonstrates adding function calls to a CoreStep.
This example isn't really interactive, should probably just be an integration test?

2023-07-25 02:08 UTC, kafischer commented
Or at least like a .nextWithFuctions so the effect is isolated?

2023-07-25 14:11 UTC, tobowers commented
> Very cool!
> 
> I'm not sure I understand the api being withFunctions versus requiring the FunctionRunner to always be specified in a .next step- it feels like it breaks something conceptually to me

I can see that. OpenAI seems to think functions live above the conversation instead of part of the conversation, but I can see how that's a little different than here. I think conceptually to me it makes sense that they are similar to memories, but I adjusted to make it more incremental and part of the `next()` call now.

2023-07-25 14:12 UTC, tobowers commented
> Or at least like a .nextWithFuctions so the effect is isolated?

Made this an optional addition to the .next() call

2023-07-25 14:28 UTC, kafischer commented
I'm sure you're seeing something here that I'm not quite yet - I am interested to understand your point

2023-07-25 14:28 UTC, kafischer approved these changes

2023-07-25 14:30 UTC, merged