add the in-memory memorystream
opensouls/SocialAGI pull request #87
Opened 2023-10-04 16:18 UTC by tobowers

Adds an in-memory scored MemoryStream to the repo which is useful for lots of usecases around keeping track of dialog, choosing appropriate conversational programs, etc.

2023-10-04 22:14 UTC, kafischer requested changes

2023-10-04 22:14 UTC, kafischer commented on memory/package.json
> +  "name": "socialagi-memory",
@socialagi/memory ?

2023-10-05 08:27 UTC, tobowers commented on memory/package.json
> +  "name": "socialagi-memory",
yup!

2023-10-05 08:27 UTC, tobowers commented
@kafischer I added the loaders package to this PR too.

2023-10-05 15:17 UTC, tobowers commented
changed loaders -> tools

2023-10-05 16:54 UTC, kafischer approved these changes

2023-10-05 16:55 UTC, merged