remove soul docs
opensouls/SocialAGI pull request #97
Opened 2023-10-12 10:11 UTC by tobowers

* Remove Soul class mentions from the docs
* fix bug at least locally trying to load non-existent file
* upgrade docusaurus

Note this has #96 in it, so once that's merged this will be a smaller PR.

2023-10-12 17:17 UTC, kafischer requested changes

2023-10-12 17:17 UTC, kafischer commented on core/src/next/cognitiveFunctions.ts
> +      ${name} should respond as if they were spekaing out loud. The response should be short (as most speech is short), include appropriate verbal ticks, use all caps when SHOUTING, and use punctuati
```suggestion
      ${name} should respond as if they were speaking out loud. The response should be short (as most speech is short), include appropriate verbal ticks, use all caps when SHOUTING, and use punctuation (such as ellipses) to indicate pauses and breaks.
```

2023-10-12 17:34 UTC, tobowers commented
@kafischer updated this branch to be based on the fixed #96

2023-10-12 17:36 UTC, tobowers commented
and now updated to main

2023-10-15 01:47 UTC, kafischer approved these changes

2023-10-15 01:47 UTC, kafischer commented
Do you have deploy access here? Or do i need to add you

2023-10-16 10:24 UTC, merged